sudo: required
services:
  - docker

before_install:
  - docker build -t zf97/docker-multicontainer -f ./client/Dockerfile.dev ./client

script:
  - docker run zf97/docker-multicontainer npm test -- --coverage

after_success:
  #Build production versions of each image
  - docker build -t zf97/multi-client ./client
  - docker build -t zf97/multi-server ./server
  - docker build -t zf97/multi-nginx ./nginx
  - docker build -t zf97/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to docker hub
  - docker push zf97/multi-client
  - docker push zf97/multi-server
  - docker push zf97/multi-nginx
  - docker push zf97/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-multicontainer
  env: DockerMulticontainer-env
  bucket_name: elasticbeanstalk-us-east-1-649508795262
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

